### ISSUE TITLE
fatal errors thrown when &ensp characters present in configs

### ISSUE THREAD

**Issue by josephrdsmith** [chef/mixlib-config#25]
If a user copies config statements from a browser, there may be &ensp or other special WWW characters present.  This will break chef-server-ctl reconfigures.

https://github.com/opscode/omnibus-analytics/issues/95 for reference.

**Comment by lamont-granquist** [comment]
well those are gonna be ruby parsing errors and its just ruby code.  think this is a bug for the website to produce code blocks that are correctly copypasta'able, its gonna be much easier to fix that.
